### ISSUE TITLE
SDK.js does not adequately warn if a malformed module.json is built

### ISSUE THREAD

**Issue by herrold** [OutbreakInc/Galago#4]
This set: https://github.com/OutbreakInc/Galago/wiki/Getting-started-guide

[herrold@centos-6 galago]$ wget http://moduleverse.com/v1/modules/logiblock/platform/0.9.12/gz  
 ... snip ...
2013-07-02 11:47:25 (379 KB/s) - “gz” saved [451556/451556]

[herrold@centos-6 galago]$ tar -zxf gz 
[herrold@centos-6 galago]$ ls  
bin  galago  gz  module.json  nxp  targets.json
[herrold@centos-6 galago]$ ls bin  
GalagoServer-linux64  GalagoServer-win32.exe  package.json     SDK.js
GalagoServer-Mac      node_modules            pty.js-prebuilt  
[herrold@centos-6 galago]$ node  bin/SDK.js  
Did not find an SDK on your system.  I will try to download the latest one
 and then build your project.  
Note: you must have an internet connection to update.  
Downloaded and installed successfully!  
Building...                                                               

/home/herrold/galago/bin/SDK.js:253
                paths.forEach(function(source)
                      ^
TypeError: Cannot call method 'forEach' of undefined
    at Object.module.exports.Toolchain.resolvePaths (/home/herrold/galago/bin/SDK.js:253:9)
    at Object.module.exports.Toolchain.compile (/home/herrold/galago/bin/SDK.js:311:27)
    at build (/home/herrold/galago/bin/SDK.js:678:20)
    at /home/herrold/galago/bin/SDK.js:703:6
    at Object.<anonymous> (/home/herrold/galago/bin/SDK.js:233:4)
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
[herrold@centos-6 galago]$ rpm -q nodejs
nodejs-0.10.12-1.orc6.x86_64
[herrold@centos-6 galago]$

**Comment by kuym** [comment]
What's happening is that the project definition lacks any files to build, and there's no check for that case. I've added checks and appropriate error reporting that will go out in the next version.  As for why there are no files, it is probably either an invalid "compatibleWith" section of the `module.json` file that defines your project, or a broken installation.  The `--init` argument to SDK.js should generate a valid `module.json` project file that can act as a starting point, and you can check the [project file documentation](https://github.com/OutbreakInc/Galago/wiki/Project-files) for a better explanation.  I'll close this issue only when I know SDK.js correctly handles non-building project files correctly.

Thanks for your report!

**Comment by kuym** [comment]
Got it: You built in the Logiblock Platform root directory, which, because the platform is itself a module just like regular project, contains a module.json file.  Confusingly, SDK.js will try to build it at that location and fail.  I've updated the Platform to [**0.9.16**](http://moduleverse.com/v1/modules/logiblock/platform/0.9.16/gz) with additional warnings and amended the [Getting Started Guide](https://github.com/OutbreakInc/Galago/wiki/Getting-started-guide) to clarify the need for a new directory for your project.  I just tested in a few configurations and will mark this issue closed unless we see additional problems.  Thanks again!
